version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - "4001:80"
    networks:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html

  php:
    build: ./app
    networks:
      - backend
    volumes:
      - ./app:/var/www/html
    secrets:
      - mysql_user_password

  mysql:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_password
      - mysql_user_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - "6001:80"
    networks:
      - backend
    secrets:
      - mysql_root_password

networks:
  frontend:
  backend:

volumes:
  mysql_data:

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_user_password:
    file: ./secrets/mysql_user_password

